//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XMLTools.rc
//
#define IDD_INPUTDLG                    2000
#define IDC_STATIC_CAPTION              2000
#define IDC_EDIT_INPUT                  2001
#define IDD_XPATHEVAL                   2001
#define IDC_EDIT_EXPRESSION             2002
#define IDD_SELECTFILE                  2002
#define IDC_LIST_NODESRESULT            2003
#define IDD_MESSAGEDLG                  2003
#define IDC_BTN_EVALUATE                2004
#define IDD_XSLTDLG                     2004
#define IDC_LIST_XPATHRESULTS           2005
#define IDD_HOWTOUSE                    2005
#define IDC_BTN_EVALUATE2               2006
#define IDC_BTN_COPY2CLIPBOARD          2006
#define IDD_ABOUTBOX                    2006
#define IDC_EDIT_FILENAME               2007
#define IDD_OPTIONS                     2007
#define IDC_BTN_EXPLORE_XSDFILE         2008
#define IDC_BTN_CLEARLIST               2008
#define IDD_DLGDEBUG                    2008
#define IDC_EDIT_ROOTELEMSAMPLE         2009
#define IDC_EDIT_MULTILINEMSG           2010
#define IDC_EDIT_XSLTFILE               2011
#define IDC_BTN_BROWSEXSLTFILE          2012
#define IDD_DIALOG1                     2012
#define IDC_EDIT_XSLTOPTIONS            2013
#define IDC_BTN_TRANSFORM               2014
#define IDC_LIST1                       2015
#define IDC_EXTLIBS_URL                 2018
#define IDC_EXTLIBS_URL4                2019
#define IDC_EXTLIBS_URL2                2019
#define IDC_ABOUTTEXT                   2019
#define IDB_NEXT                        2019
#define IDC_ABOUTURL                    2020
#define IDB_PREV                        2020
#define IDB_CHECKXML                    2021
#define IDC_CHKENABLEPROXY              2022
#define IDB_VALIDATEXML                 2022
#define IDC_EDITPROXYHOST               2023
#define IDC_EDITPROXYPORT               2024
#define IDB_COMMENT                     2024
#define IDC_EDITPROXYUSERNAME           2025
#define IDB_CURRENTXPATH                2025
#define IDC_EDITPROXYPASSWORD           2026
#define IDB_CURRENTXPATHNS              2026
#define IDC_BUTTON1                     2027
#define IDB_ESCAPE                      2028
#define IDC_EDITDEBUG                   2029
#define IDB_EVALUATEXPATH               2029
#define IDC_CHKPROHIBITDTD              2030
#define IDB_LINEARIZE                   2030
#define IDC_EDIT_NAMESPACE              2031
#define IDB_OPTIONS                     2031
#define IDC_STATIC_XPATH                2032
#define IDB_PRETTYPRINT                 2032
#define IDC_STATIC_NS                   2033
#define IDB_PRETTYPRINTINDENTATTR       2033
#define IDC_STATIC_INFOS                2034
#define IDB_PRETTYPRINTINDENTONLY       2034
#define IDB_UNCOMMENT                   2035
#define IDC_CHKANNOTATIONS              2036
#define IDB_UNESCAPE                    2036
#define IDB_XSLTRANSFORM                2037
#define IDC_EDITANNOTATIONSTYLE         2038
#define IDC_BTNVIEWANNOTATION           2039
#define IDB_FIRST                       2039
#define IDC_CHKLT                       2040
#define IDB_BITMAP2                     2040
#define IDB_LAST                        2040
#define IDC_CHKGT                       2041
#define IDI_CHECKXML                    2041
#define IDI_CHECKXML_DM                 2042
#define IDC_CHKQUOTE                    2043
#define IDI_COMMENT                     2043
#define IDC_CHKAMP                      2044
#define IDI_COMMENT_DM                  2044
#define IDC_CHECK5                      2045
#define IDC_CHKAPOS                     2045
#define IDI_CURRENTXPATH                2045
#define IDC_CHECK1                      2046
#define IDC_CHKPPAUTOCLOSE              2046
#define IDI_CURRENTXPATH_DM             2046
#define IDC_CHECK2                      2047
#define IDC_CHKMULTIPLEERRORS           2047
#define IDI_CURRENTXPATHNS              2047
#define IDI_CURRENTXPATHNS_DM           2048
#define IDC_PROPERTIES                  2051
#define IDI_ESCAPE                      2051
#define IDI_ESCAPE_DM                   2052
#define IDC_BTNCLEAR                    2053
#define IDI_EVALUATEXPATH               2053
#define IDC_BTNCLOSE                    2054
#define IDI_EVALUATEXPATH_DM            2054
#define IDC_TAB1                        2055
#define IDI_FIRST                       2055
#define IDC_LNKHOMEPAGE                 2056
#define IDI_FIRST_DM                    2056
#define IDI_LAST                        2057
#define IDI_LAST_DM                     2058
#define IDI_LINEARIZE                   2059
#define IDI_LINEARIZE_DM                2060
#define IDI_NEXT                        2061
#define IDI_NEXT_DM                     2062
#define IDI_OPTIONS                     2063
#define IDI_OPTIONS_DM                  2064
#define IDI_PRETTYPRINT                 2065
#define IDI_PRETTYPRINT_DM              2066
#define IDI_PRETTYPRINTINDENTATTR       2067
#define IDI_PRETTYPRINTINDENTATTR_DM    2068
#define IDI_PRETTYPRINTINDENTONLY       2069
#define IDI_IDI_PRETTYPRINTINDENTONLY_DM 2070
#define IDI_PRETTYPRINTINDENTONLY_DM    2070
#define IDI_PREV                        2071
#define IDI_PREV_DM                     2072
#define IDI_UNCOMMENT                   2073
#define IDI_UNCOMMENT_DM                2074
#define IDI_UNESCAPE                    2075
#define IDI_UNESCAPE_DM                 2076
#define IDI_VALIDATEXML                 2077
#define IDI_VALIDATEXML_DM              2078
#define IDI_XSLTRANSFORM                2079
#define IDI_XSLTRANSFORM_DM             2080

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2081
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2057
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
